/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banco;

import javax.swing.JOptionPane;

/**
 *
 * @author Gabriela
 */
public class Banco extends javax.swing.JFrame {

    /**
     * Creates new form Banco
     */
    public Banco() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        fld_nome = new javax.swing.JTextField();
        rb_normal = new javax.swing.JRadioButton();
        rb_especial = new javax.swing.JRadioButton();
        cb_operacao = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Nome:");

        buttonGroup1.add(rb_normal);
        rb_normal.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        rb_normal.setText("Cliente Normal");

        buttonGroup1.add(rb_especial);
        rb_especial.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        rb_especial.setText("Cliente Especial");

        cb_operacao.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cb_operacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SACAR", "DEPOSITAR" }));

        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setText("Confirma");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(fld_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rb_normal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(rb_especial)
                        .addGap(70, 70, 70))))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(cb_operacao, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fld_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_normal)
                    .addComponent(rb_especial))
                .addGap(28, 28, 28)
                .addComponent(cb_operacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double saldo = 750;
       if(rb_normal.isSelected()){
           if(cb_operacao.getSelectedIndex()== 0){
             Double valor = Double.parseDouble(JOptionPane.showInputDialog("Valor que deseja sacar: ")); 
             if(valor > saldo){
                 JOptionPane.showMessageDialog(null,"Saldo Insuficiente","SaldoInsuficiente",
                         JOptionPane.ERROR_MESSAGE);
             }else{
                 double imposto = valor * 0.3;
                 saldo = saldo - (valor + imposto);
                 JOptionPane.showMessageDialog(null,fld_nome.getText() + "\n Valor sacado: " +
                         valor + "\nImposto cobrado: " + imposto + ""
                                 + "\nSaldo atual: " + saldo);
                 
                }
            }
           if(cb_operacao.getSelectedIndex() == 1){
               Double valor = Double.parseDouble(JOptionPane.showInputDialog("Valor que deseja depositar: "));
               saldo +=valor;
               JOptionPane.showMessageDialog(null,fld_nome.getText() + "\nValor depositado: " + valor 
               + "\nSaldo atual: " + saldo);
            }
       }
       if(rb_especial.isSelected()){
           if(cb_operacao.getSelectedIndex()==0){
              Double valor = Double.parseDouble(JOptionPane.showInputDialog("Valor que deseja sacar: ")); 
             if(valor > saldo){
                 JOptionPane.showMessageDialog(null,"Saldo Insuficiente","SaldoInsuficiente",
                         JOptionPane.ERROR_MESSAGE);
             }else{
                 double imposto = valor * 0.1;
                 saldo = saldo - (valor + imposto);
                 JOptionPane.showMessageDialog(null,fld_nome.getText() + "\n Valor sacado: " +
                         valor + "\nImposto cobrado: " + imposto + ""
                                 + "\nSaldo atual: " + saldo);
                 
                }
            }
           if(cb_operacao.getSelectedIndex() == 1){
               Double valor = Double.parseDouble(JOptionPane.showInputDialog("Valor que deseja depositar: "));
               saldo +=valor;
               JOptionPane.showMessageDialog(null,fld_nome.getText() + "\nValor depositado: " + valor 
               + "\nSaldo atual: " + saldo);
            } 
           
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Banco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Banco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Banco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Banco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Banco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb_operacao;
    private javax.swing.JTextField fld_nome;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton rb_especial;
    private javax.swing.JRadioButton rb_normal;
    // End of variables declaration//GEN-END:variables
}
